# This file defines conventions for where SegTraQ stores its results in the AnnData object.
# This is to avoid conflicts with other tools and to make it clear which data is generated by SegTraQ.

# ── Layers ────────────────────────────────────────────────────────────────────
NORM_LOG_LAYER = "norm_log_segtraq"

# ── Highly variable genes ─────────────────────────────────────────────────────
HVG_KEY = "highly_variable_segtraq"
HVG_PANEL_SIZE_THRESHOLD = 8_000
N_HVG = 2_000

# ── Obsm ──────────────────────────────────────────────────────────────────────
PCA_KEY = "X_pca_segtraq"

# ── Uns ───────────────────────────────────────────────────────────────────────
NEIGHBORS_KEY = "neighbors_segtraq"
PCA_NEIGHBORS_CONFIG_KEY = "pca_neighbors_config_segtraq"

# ── Obsp ──────────────────────────────────────────────────────────────────────
CONNECTIVITIES_KEY = "connectivities_segtraq"
DISTANCES_KEY = "distances_segtraq"

# ── Cell ID ───────────────────────────────────────────────────────────────────
SEGTRAQ_CELL_ID_KEY = "segtraq_id"
