# This file defines conventions for where SegTraQ stores its results in the AnnData object.
# This is to avoid conflicts with other tools and to make it clear which data is generated by SegTraQ.

# ── Layers ────────────────────────────────────────────────────────────────────
NORM_LOG_LAYER = "norm_log_segtraq"

# ── Obsm ──────────────────────────────────────────────────────────────────────
PCA_KEY = "X_pca_segtraq"

# ── Uns ───────────────────────────────────────────────────────────────────────
NEIGHBORS_KEY = "neighbors_segtraq"

# ── Obsp ──────────────────────────────────────────────────────────────────────
CONNECTIVITIES_KEY = "connectivities_segtraq"
DISTANCES_KEY = "distances_segtraq"

# ── Cell ID ───────────────────────────────────────────────────────────────────
SEGTRAQ_CELL_ID_KEY = "segtraq_id"
