# name: Build and Deploy Docs

# on:
#   push:
#     # TODO: should change this to only deploy on main branch!
#     branches-ignore:
#       - gh-pages
#       - docs

# permissions:
#   contents: read
#   pages: write
#   id-token: write

# jobs:
#   docs:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: 3.12
#     - name: Install documentation dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install sphinx sphinx-rtd-theme
#     - name: Build documentation
#       run: |
#         cd docs
#         make html
#     - name: Deploy to GitHub Pages
#       uses: peaceiris/actions-gh-pages@v4
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: ./docs/_build/html
