name: Test and Deploy Docs

on:
  push:
    branches:
      - main
    branches-ignore:
      - gh-pages
      - docs
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read
  pages: write          # needed to deploy pages
  id-token: write       # for deployment authentication

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12', '3.13']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies using uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        uv pip install -e ".[test]" --system
    - name: Lint with ruff
      run: |
        ruff check --select=E9,F63,F7,F82
        ruff check --exit-zero --statistics
    - name: Run tests
      run: pytest

  docs:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install documentation dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme  # adjust if you use other tools, e.g. pdoc or mkdocs

    - name: Build documentation
      run: |
        cd docs
        make html  # or sphinx-build -b html . _build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        # Optional: configure cname, user_name, user_email here
